- name: Deploy posts
  hosts: 
   - projet_de_specialite_instance_private_posts
  tasks:
   - name: Install git and python3-pip
     apt:
       pkg:
       - git
       - python3-pip
       state: latest
       update_cache: true
   - name: Create directory /opt/posts
     file:
       path: /opt/posts
       state: directory
       mode: "0755"
   - name: Clone Git repository
     git:
       repo: https://github.com/projet-de-specialite/posts-old
       dest: /opt/posts
       version: main
       force: yes
   - name: Install Python dependencies
     pip:
       requirements: /opt/posts/project/requirements.txt
       state: present