- name: Deploy comments
  hosts: 
   - projet_de_specialite_instance_private_comments
  tasks:
    - name: Create comments group
     group:
       name: comments
       state: present
    - name: create comments user
     user:
       name: comments
       groups: comments
       shell: /sbin/nologin
       append: yes
       state: present
       create_home: no
    - name: Create a directory if it does not exist
      file:
        path: /opt/commentaires
        state: directory
        mode: "0755"
        owner: comments
        group: comments
    - name: Download a file from a remote server
      get_url:
        url: https://github.com/projet-de-specialite/Commentaires/releases/latest/download/commentaires-linux-amd64
        dest: /opt/commentaires/commentaires-linux-amd64
        mode: "0755"
        owner: comments
        group: comments
    - name: Copy systemd service file to server
      copy:
       src: ./service/comments.service
       dest: /etc/systemd/system
       owner: root
       group: root
    - name: Start comments
      systemd:
       name: comments
       state: started
       enabled: yes
