- name: Install gcsfuse, mount bucket and reboot
  hosts: 
   - projet_de_specialite_instance_private_posts
   - projet_de_specialite_instance_private_profile
  tasks:
   - name: Get Google Cloud Package GPG key
     get_url:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      dest: /etc/apt/trusted.gpg.d/gcsfuse.gpg
   - name: Add Google Cloud Packages repo
     apt_repository: 
       repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/gcsfuse.gpg] https://packages.cloud.google.com/apt gcsfuse-{{ ansible_distribution_release }} main"
       filename: gcsfuse
       state: present
   - name: Install gcsfuse
     apt:
       pkg:
       - gcsfuse
       state: latest
       update_cache: true
   - name: Create bucket directory
     file:
       path: "/mnt/{{ bucket }}/"
       state: directory
       mode: 0755
       owner: root
       group: root
   - name: Mount bucket
     mount:
      src: "{{ bucket }}"
      path: "/mnt/{{ bucket }}"
      opts: rw,_netdev,allow_other,file_mode=0666,dir_mode=0777
      boot: true
      state: mounted
      fstype: gcsfuse